### ISSUE TITLE
SigKill Illegal Instruction on Debian Testing wayland and Debian 10 stable X11

### ISSUE THREAD

**Issue by defdefred** [skyjake/lagrange#38]
[strace.txt](https://github.com/skyjake/lagrange/files/5542774/strace.txt)

**Comment by skyjake** [comment]
- Did you build from source?
- Does launching with the `--sw` option make a difference?
- Would be helpful to see a debug build backtrace from gdb to pinpoint where the SIGILL occurs.
- Which distro is the strace.txt from?

**Comment by defdefred** [comment]
I use your debian release.
strace is from debian testing.
`--sw` make no difference.
Will try to use gdb :-)

**Comment by defdefred** [comment]
[gdb1.txt](https://github.com/skyjake/lagrange/files/5548752/gdb1.txt)

**Comment by skyjake** [comment]
Thanks. 👍  One more thing: could you enter a `bt` command in gdb after the crash? Seeing the backtrace should fill in the blanks.

> I use your debian release.

Hmm, this is GitHub-built so the details are a bit out of our control. I believe it uses Debian Buster inside a Docker container to do the build, but it's conceivable that something goes awry in the build config.

**Comment by defdefred** [comment]
[bt.txt](https://github.com/skyjake/lagrange/files/5555144/bt.txt)

**Comment by skyjake** [comment]
Not sure what could be the issue here... The only thing I can think of is that around the_Foundation/src/block.c:63 it is manipulating an atomic integer and perhaps the compiler in the GitHub CI environment generates some CPU instructions that are not supported on your system with regard to atomics? Or maybe some subtle C runtime version mismatch? Seems strange though.

Have you tried a build from source on your system(s)?

**Comment by defdefred** [comment]
Hi skyjake,

Build from source give the same issue.

[build.txt](https://github.com/skyjake/lagrange/files/5578277/build.txt)

**Comment by skyjake** [comment]
I tried a build myself in a Debian Buster VM and unfortunately couldn't see any problems with running Lagrange.

This may be an issue that's somehow specific to your system. Could you share some details about the hardware and exact Debian distro version?

**Comment by skyjake** [comment]
Please see #91. It turned out that setting the CMake variable `TFDN_ENABLE_SSE41` to `OFF` fixed a similar illegal instruction issue.

**Comment by skyjake** [comment]
@defdefred May now be fixed in v0.12.1, please confirm...

**Comment by defdefred** [comment]
Issue still here:
```
$ ./Lagrange-1.15.1-x86_64.AppImage 
Segmentation fault
```
The testing computosaure is a Wyse thin client/
```
processor       : 1
vendor_id       : AuthenticAMD
cpu family      : 20
model           : 2
model name      : AMD G-T56N Processor
stepping        : 0
microcode       : 0x5000101
cpu MHz         : 1629.406
cache size      : 512 KB
physical id     : 0
siblings        : 2
core id         : 1
cpu cores       : 2
apicid          : 1
initial apicid  : 1
fpu             : yes
fpu_exception   : yes
cpuid level     : 6
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1
gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf pni monitor ssse3 cx16 popcnt lahf_lm cmp_legacy svm extapic cr8_legac
y abm sse4a misalignsse 3dnowprefetch ibs skinit wdt hw_pstate vmmcall arat npt lbrv svm_lock nrip_save pausefilter
bugs            : fxsave_leak sysret_ss_attrs null_seg spectre_v1 spectre_v2 spec_store_bypass
bogomips        : 3293.07
TLB size        : 1024 4K pages
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management: ts ttp tm stc 100mhzsteps hwpstate
```

**Comment by skyjake** [comment]
Looking at some specs, the G-T56N was released in 2010, so perhaps this is just a case of the CPU being a bit too old? AppImages aren't intended to be universally compatible.

This could probably be fixed by changing the compiler options for the AppImage but I have no idea which ones would work in this case.
